add oauth
maxpavlovdp/activecharge pull request #242
Opened 2022-12-11 10:23 UTC by vdvoretskyi

2022-12-11 18:19 UTC, maxpavlovdp commented on src/main/java/com/km220/dao/station/StationRepositoryV2.java
> +  StationEntity findByNumber(String number);
this what I wanted

2022-12-24 13:14 UTC, maxpavlovdp requested changes

2022-12-24 13:40 UTC, maxpavlovdp commented
1. monobank callback faces 401 I believe
2. 401 erro is used in ewelink and in our logic. Is it ok?
<img width="671" alt="image" src="https://user-images.githubusercontent.com/5563023/209438480-539e7f2e-f989-4f5b-909c-a3200ca56b8e.png">
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/5563023/209438487-6573354e-7a74-4c5c-be63-f51f1011f79f.png">

2022-12-24 13:49 UTC, maxpavlovdp commented
user km220.com@gmail.com should see only station 1

2022-12-24 14:11 UTC, dimaborbotko commented on src-js/react/src/App/adminPage/AdminPage.tsx
>  import "./adminPage.css";
renamed

2023-01-04 09:20 UTC, maxpavlovdp commented
http://49.12.19.42:8080/swagger-ui/index.html#/order-controller/callBackMono

2023-01-12 14:03 UTC, merged